### ISSUE TITLE
[BUG] Exam mode result points are wrong

### ISSUE THREAD

**Issue by 0xJohnnyboy** [Ditectrev/Practice-Exams-Platform#31]
**Describe the bug**
Results page seems to show a wrong number of points, at least for the PSD-1 exam mode.

**To Reproduce**
1. PSD-1
2. Click on Exam Mode
3. Open Network tab to make sure all the answers are valid
4. It shows a 96.67% score. 

**Expected behavior**

**Screenshots**
I expect the app to show 100% when I do 100%

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Arc
 - Version: Arc: Based on Chromium version 126.0.6478.57

**Additional context**
I tried the other way around: having only 1 good answer gives me 3.33/100 which is good.

I would have looked into it but I can't seem to run the app locally at the moment on my work laptop (next dev weirdly fails immediately without any error message). Maybe later in the week.

**Comment by danieldanielecki** [comment]
Thanks for submitting the issue; somehow, it slipped from all my notifications.

Please keep me posted if you'll be able to pick it up :)

**Comment by danieldanielecki** [comment]
Maybe an idea to combine it with summary page for `Practice Mode`?
https://github.com/Ditectrev/Practice-Exams-Platform/issues/34

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Practice-Exams-Platform/pull/45.
