### ISSUE TITLE
[QUESTION] Question

### ISSUE THREAD

**Issue by Natsuki-R** [Ditectrev/Practice-Exams-Platform#48]
### Question name  
**AWS Certified CLF-C02, Sequence 578**  

[README.md&name=AWS+Certified+CLF-C02&seq=578](https://education.ditectrev.com/practice?url=https%3A%2F%2Fraw.githubusercontent.com%2FDitectrev%2FAmazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers%2Fmain%2FREADME.md&name=AWS+Certified+CLF-C02&seq=578)

### What is the issue?  
On the website, the question displays only the first two options instead of all four options. This is inconsistent with the data in the `README.md`. It seems the source code might be missing part of the data for this question.  

<img width="1223" alt="スクリーンショット 2024-12-13 13 12 13" src="https://github.com/user-attachments/assets/98fe4e48-d838-433c-b7a8-182712f85fbc" />

### What is the solution?  
Ensure that all four options are displayed correctly on the website as per the `README.md`. Below is the full question with correct formatting:  

**How do Amazon EC2 Auto Scaling groups help achieve high availability for a web application?**  
- [ ] They automatically add more instances across multiple AWS Regions based on global demand of the application.  
- [x] They automatically add or replace instances across multiple Availability Zones when the application needs it.  
- [ ] They enable the application's static content to reside closer to end users.  
- [ ] They are able to distribute incoming requests across a tier of web server instances.

**Comment by danieldanielecki** [comment]
Thanks for the information, but I see that's just 1 question (out of thousands). It might be a lot of effort to debug it. 

Please submit a pull request if you find it, but I'm not planning to pick it up given the effort-to-gain ratio.

**Comment by danieldanielecki** [comment]
https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/810aeb0eea2ed0f53d5203ceb8d869f4040e6878 should fix it.

**Comment by danieldanielecki** [comment]
and it did ;-)

![Screenshot 2024-12-23 at 13 24 19](https://github.com/user-attachments/assets/ca66eaa0-508e-4de5-93b1-ea6d3eeb3e3e)
